server:
    port: 
    servlet:
        encoding:
            force: true

spring:
    datasource:
        url: 
        username: 
        password: 
        hikari:
            auto-commit: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        open-in-view: false
    servlet:
        multipart:
            max-request-size: 20MB
            max-file-size: 10MB

system:
    filePath:
        base: 
        uploads: 
